# Generated by Django 5.0.2 on 2024-03-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='read_books',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
